### ISSUE TITLE
Migrate the bot to Slash Commands

### ISSUE THREAD

**Issue by Logan9312** [Sooraj-beep/sherp2.0#44]
They are better and cooler than text commands

**Comment by Sooraj-beep** [comment]
Agreed

**Comment by Logan9312** [comment]
If nobody has picked this issue by the time I finish with schedubuddy sharing and reworking my own bot I'll do it

**Comment by aarctan** [comment]
@ArtDynasty13 are you interested in this?

**Comment by ArtDynasty13** [comment]
> @ArtDynasty13 are you interested in this?

Yeah, I'll take a look at it if no one gets to it quicker but idk when that will be...
