### ISSUE TITLE
Add config file instead of hardcoding values in code.

### ISSUE THREAD

**Issue by DhanrajHira** [Sooraj-beep/sherp2.0#54]
Currently a lot of things like (like starboard threshold, emoji and channel) are configured by setting them directly in the python code. This makes testing a pain where things must be changed back before the final commit. Its better to have a config file that is not tracked by git to take care of these things.

We need to decide on a config format as well. Python stdlib has parsers for INI and TOML if we want to go that route or we can just use plain old json. I am leaning towards TOML.

**Comment by DhanrajHira** [comment]
Work done. Waiting for #52 to land before I file the PR for this.

**Comment by aarctan** [comment]
Valid suggestion although I prefer that things like starboard emoji and threshold be visible in the source somehow. would your change hide these?

**Comment by DhanrajHira** [comment]
@aarctan The defaults are still in the code (The ones we use for CS Discord). If the config file is present and has that specific parameter then the config file values are used.

**Comment by Sooraj-beep** [comment]
We can close this issue now right?
